// 사람인 API 키 발급 전 임시 mock 데이터 — UI 확인용
import type { Job } from './types'

const now = new Date()
const days = (n: number) => new Date(now.getTime() + n * 86400000).toISOString()

export const MOCK_JOBS: Partial<Job>[] = [
  {
    id: 1,
    source: 'manual',
    source_id: 'mock-1',
    url: 'https://example.com/jobs/1',
    company_name: '토스',
    title: '서비스 기획자 (PM) — 결제 프로덕트',
    category_raw: 'PM/PO',
    experience_level: '경력 3~7년',
    experience_min: 3,
    experience_max: 7,
    employment_type: '정규직',
    location: '서울 강남구',
    salary: '회사 내규에 따름',
    jd_text: '결제 프로덕트의 사용자 경험을 책임지고, 데이터 기반으로 의사결정합니다.\n• 사용자 페인포인트 분석 및 우선순위 정의\n• 디자이너/엔지니어와 협업하여 기능 출시\n• A/B 테스트를 통한 가설 검증',
    requirements: '• 3년 이상의 프로덕트 매니지먼트 경험\n• 데이터 분석 도구 활용 능력 (SQL, Amplitude 등)\n• 커뮤니케이션 역량',
    preferred: '• 핀테크/결제 도메인 경험\n• 스타트업 초기 멤버 경험',
    company_industry: '핀테크',
    company_size: '1000명 이상',
    deadline: days(14),
    posted_at: days(-2),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['유망스타트업', '경력추천'],
    selection_process: '서류 → 1차 인터뷰 → 과제 → 임원면접',
    created_at: days(-2),
    updated_at: days(-2),
  },
  {
    id: 2,
    source: 'manual',
    source_id: 'mock-2',
    url: 'https://example.com/jobs/2',
    company_name: '당근',
    title: '브랜드 마케터 (Brand Marketing Manager)',
    category_raw: '마케팅',
    experience_level: '경력 5년 이상',
    experience_min: 5,
    employment_type: '정규직',
    location: '서울 서초구',
    salary: null,
    jd_text: '당근의 브랜드 캠페인을 기획하고 실행합니다.\n• 통합 마케팅 캠페인 설계\n• 외부 에이전시 협업 리딩\n• 브랜드 자산 관리',
    requirements: '• 브랜드 마케팅 5년 이상\n• 통합 캠페인 리딩 경험',
    preferred: '• 플랫폼 서비스 경험',
    company_industry: 'IT 플랫폼',
    company_size: '500~999명',
    deadline: days(21),
    posted_at: days(-1),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['대기업'],
    created_at: days(-1),
    updated_at: days(-1),
  },
  {
    id: 3,
    source: 'manual',
    source_id: 'mock-3',
    url: 'https://example.com/jobs/3',
    company_name: '컬리',
    title: '신입 서비스 기획자 (대졸 공채)',
    category_raw: '기획',
    experience_level: '신입',
    experience_min: 0,
    experience_max: 0,
    employment_type: '정규직',
    location: '서울 강남구',
    jd_text: '신선식품 커머스의 사용자 여정을 기획합니다.\n• 고객 행동 분석\n• 화면 설계 및 정책 정의',
    requirements: '• 4년제 대졸 이상\n• 기획 인턴 또는 프로젝트 경험',
    preferred: '• 커머스 도메인 관심',
    company_industry: '이커머스',
    company_size: '500~999명',
    deadline: days(7),
    posted_at: days(-3),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['신입추천'],
    selection_process: '서류 → 인적성 → 1차 면접 → 임원면접',
    created_at: days(-3),
    updated_at: days(-3),
  },
  {
    id: 4,
    source: 'manual',
    source_id: 'mock-4',
    url: 'https://example.com/jobs/4',
    company_name: '리디',
    title: '퍼포먼스 마케터 (신입/주니어)',
    category_raw: '마케팅',
    experience_level: '신입~3년',
    experience_min: 0,
    experience_max: 3,
    employment_type: '정규직',
    location: '서울 강남구',
    jd_text: '디지털 광고 채널 운영과 그로스 실험을 담당합니다.\n• 검색/디스플레이/SNS 광고 운영\n• ROAS 최적화\n• 그로스 실험 설계',
    requirements: '• 디지털 마케팅에 관심',
    preferred: '• GA, Meta Ads 경험',
    company_industry: '콘텐츠',
    company_size: '300~499명',
    deadline: days(10),
    posted_at: days(-1),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['신입추천'],
    created_at: days(-1),
    updated_at: days(-1),
  },
  {
    id: 5,
    source: 'manual',
    source_id: 'mock-5',
    url: 'https://example.com/jobs/5',
    company_name: '오늘의집',
    title: '사업개발 매니저 (BD)',
    category_raw: '사업기획',
    experience_level: '경력 4년 이상',
    experience_min: 4,
    employment_type: '정규직',
    location: '서울 서초구',
    jd_text: '신규 사업 영역 발굴 및 파트너십을 담당합니다.',
    requirements: '• 컨설팅, BD, 사업기획 경력 4년 이상',
    preferred: '• 커머스 또는 플랫폼 도메인 경험',
    company_industry: 'IT 플랫폼',
    company_size: '500~999명',
    deadline: days(30),
    posted_at: days(-5),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['대기업'],
    created_at: days(-5),
    updated_at: days(-5),
  },
]
