// 사람인 API 키 발급 전 임시 mock 데이터 — UI 확인용
import type { Job } from './types'

const now = new Date()
const days = (n: number) => new Date(now.getTime() + n * 86400000).toISOString()

export const MOCK_JOBS: Partial<Job>[] = [
  // ── 채용 (정규직) ──────────────────────────────────────
  {
    id: 1,
    source: 'manual',
    source_id: 'mock-1',
    content_type: 'job',
    url: 'https://example.com/jobs/1',
    company_name: '토스',
    title: '서비스 기획자 (PM) — 결제 프로덕트',
    category_raw: 'PM/PO',
    experience_level: '경력 3~7년',
    experience_min: 3,
    experience_max: 7,
    employment_type: '정규직',
    location: '서울 강남구',
    salary: '회사 내규에 따름',
    jd_text: '결제 프로덕트의 사용자 경험을 책임지고, 데이터 기반으로 의사결정합니다.\n• 사용자 페인포인트 분석 및 우선순위 정의\n• 디자이너/엔지니어와 협업하여 기능 출시\n• A/B 테스트를 통한 가설 검증',
    requirements: '• 3년 이상의 프로덕트 매니지먼트 경험\n• 데이터 분석 도구 활용 능력 (SQL, Amplitude 등)\n• 커뮤니케이션 역량',
    preferred: '• 핀테크/결제 도메인 경험\n• 스타트업 초기 멤버 경험',
    company_industry: '핀테크',
    company_size: '1000명 이상',
    deadline: days(14),
    posted_at: days(-2),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['유망스타트업', '경력추천'],
    selection_process: '서류 → 1차 인터뷰 → 과제 → 임원면접',
    created_at: days(-2),
    updated_at: days(-2),
  },
  {
    id: 2,
    source: 'manual',
    source_id: 'mock-2',
    content_type: 'job',
    url: 'https://example.com/jobs/2',
    company_name: '당근',
    title: '브랜드 마케터 (Brand Marketing Manager)',
    category_raw: '마케팅',
    experience_level: '경력 5년 이상',
    experience_min: 5,
    employment_type: '정규직',
    location: '서울 서초구',
    salary: null,
    jd_text: '당근의 브랜드 캠페인을 기획하고 실행합니다.\n• 통합 마케팅 캠페인 설계\n• 외부 에이전시 협업 리딩\n• 브랜드 자산 관리',
    requirements: '• 브랜드 마케팅 5년 이상\n• 통합 캠페인 리딩 경험',
    preferred: '• 플랫폼 서비스 경험',
    company_industry: 'IT 플랫폼',
    company_size: '500~999명',
    deadline: days(21),
    posted_at: days(-1),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['대기업'],
    created_at: days(-1),
    updated_at: days(-1),
  },
  {
    id: 3,
    source: 'manual',
    source_id: 'mock-3',
    content_type: 'job',
    url: 'https://example.com/jobs/3',
    company_name: '컬리',
    title: '신입 서비스 기획자 (대졸 공채)',
    category_raw: '기획',
    experience_level: '신입',
    experience_min: 0,
    experience_max: 0,
    employment_type: '정규직',
    location: '서울 강남구',
    jd_text: '신선식품 커머스의 사용자 여정을 기획합니다.\n• 고객 행동 분석\n• 화면 설계 및 정책 정의',
    requirements: '• 4년제 대졸 이상\n• 기획 인턴 또는 프로젝트 경험',
    preferred: '• 커머스 도메인 관심',
    company_industry: '이커머스',
    company_size: '500~999명',
    deadline: days(7),
    posted_at: days(-3),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['신입추천'],
    selection_process: '서류 → 인적성 → 1차 면접 → 임원면접',
    created_at: days(-3),
    updated_at: days(-3),
  },
  {
    id: 4,
    source: 'manual',
    source_id: 'mock-4',
    content_type: 'job',
    url: 'https://example.com/jobs/4',
    company_name: '리디',
    title: '퍼포먼스 마케터 (신입/주니어)',
    category_raw: '마케팅',
    experience_level: '신입~3년',
    experience_min: 0,
    experience_max: 3,
    employment_type: '정규직',
    location: '서울 강남구',
    jd_text: '디지털 광고 채널 운영과 그로스 실험을 담당합니다.',
    requirements: '• 디지털 마케팅에 관심',
    preferred: '• GA, Meta Ads 경험',
    company_industry: '콘텐츠',
    company_size: '300~499명',
    deadline: days(10),
    posted_at: days(-1),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['신입추천'],
    created_at: days(-1),
    updated_at: days(-1),
  },
  {
    id: 5,
    source: 'manual',
    source_id: 'mock-5',
    content_type: 'job',
    url: 'https://example.com/jobs/5',
    company_name: '오늘의집',
    title: '사업개발 매니저 (BD)',
    category_raw: '사업기획',
    experience_level: '경력 4년 이상',
    experience_min: 4,
    employment_type: '정규직',
    location: '서울 서초구',
    jd_text: '신규 사업 영역 발굴 및 파트너십을 담당합니다.',
    requirements: '• 컨설팅, BD, 사업기획 경력 4년 이상',
    preferred: '• 커머스 또는 플랫폼 도메인 경험',
    company_industry: 'IT 플랫폼',
    company_size: '500~999명',
    deadline: days(30),
    posted_at: days(-5),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['대기업'],
    created_at: days(-5),
    updated_at: days(-5),
  },

  // ── 인턴십 ────────────────────────────────────────────
  {
    id: 6,
    source: 'manual',
    source_id: 'mock-6',
    content_type: 'intern',
    url: 'https://linkareer.com/activity/1',
    company_name: '카카오',
    title: '서비스기획 인턴 (Summer 2025)',
    category_raw: '기획',
    experience_level: '신입/인턴',
    experience_min: 0,
    experience_max: 0,
    employment_type: '인턴',
    location: '경기 성남시',
    jd_text: '카카오 서비스의 기획 업무를 직접 경험합니다.\n• UX 리서치 보조\n• 서비스 기획 문서 작성\n• 데이터 분석 기초',
    requirements: '• 학부 3~4학년 또는 졸업예정자\n• 기획 관심 및 기초 역량',
    preferred: '• 카카오 서비스 이용 경험 및 개선 아이디어',
    company_industry: 'IT 플랫폼',
    company_size: '1000명 이상',
    deadline: days(20),
    posted_at: days(-1),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['대기업 인턴', '신입추천'],
    selection_process: '서류 → 코딩테스트 → 면접',
    created_at: days(-1),
    updated_at: days(-1),
  },
  {
    id: 7,
    source: 'manual',
    source_id: 'mock-7',
    content_type: 'intern',
    url: 'https://linkareer.com/activity/2',
    company_name: '네이버',
    title: 'PM 인턴 — 검색 서비스',
    category_raw: 'PM/PO',
    experience_level: '신입/인턴',
    experience_min: 0,
    experience_max: 0,
    employment_type: '인턴',
    location: '경기 성남시',
    jd_text: '검색 서비스의 프로덕트 운영에 참여합니다.\n• 사용자 피드백 분석\n• 기능 요구사항 문서화\n• 경쟁사 서비스 벤치마킹',
    requirements: '• 대학 재학/졸업예정자 (전공 무관)\n• 논리적 사고 및 문서 작성 능력',
    preferred: '• IT 서비스 기획 프로젝트 경험',
    company_industry: 'IT',
    company_size: '1000명 이상',
    deadline: days(15),
    posted_at: days(-2),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['대기업 인턴'],
    created_at: days(-2),
    updated_at: days(-2),
  },
  {
    id: 8,
    source: 'manual',
    source_id: 'mock-8',
    content_type: 'intern',
    url: 'https://linkareer.com/activity/3',
    company_name: '무신사',
    title: '마케팅 인턴 (퍼포먼스)',
    category_raw: '마케팅',
    experience_level: '신입/인턴',
    experience_min: 0,
    experience_max: 0,
    employment_type: '인턴',
    location: '서울 성동구',
    jd_text: '퍼포먼스 마케팅 실무를 배울 수 있는 인턴십입니다.\n• SNS 광고 보조 운영\n• 리포트 작성 및 데이터 분석\n• 콘텐츠 소재 아이디어 기여',
    requirements: '• 학부 재학생 이상\n• Meta / Google 광고 기초 지식',
    preferred: '• 패션/커머스 관심자',
    company_industry: '패션 커머스',
    company_size: '500~999명',
    deadline: days(12),
    posted_at: days(-1),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['스타트업 인턴'],
    created_at: days(-1),
    updated_at: days(-1),
  },

  // ── 부트캠프 ──────────────────────────────────────────
  {
    id: 9,
    source: 'manual',
    source_id: 'mock-9',
    content_type: 'bootcamp',
    url: 'https://zerobase.kr/pm',
    company_name: '제로베이스',
    title: 'PM 스쿨 (기획·전략 집중)',
    category_raw: 'PM/PO',
    experience_level: '신입/무경력',
    experience_min: 0,
    employment_type: '부트캠프',
    location: '온라인',
    salary: '정부지원 가능 (내일배움카드)',
    jd_text: '비전공자도 3개월 안에 PM 포트폴리오를 완성합니다.\n• 프로덕트 기획 전 과정 실습\n• 현직 PM 멘토링 포함\n• 취업 연계 지원',
    requirements: '• 전공 무관\n• 기획자/PM 취업 목표',
    company_industry: '에듀테크',
    deadline: days(45),
    posted_at: days(-7),
    is_featured: true,
    is_hidden: false,
    recommendation_tags: ['내일배움카드', '취업연계'],
    created_at: days(-7),
    updated_at: days(-7),
  },
  {
    id: 10,
    source: 'manual',
    source_id: 'mock-10',
    content_type: 'bootcamp',
    url: 'https://fastcampus.co.kr/pm',
    company_name: '패스트캠퍼스',
    title: '프로덕트 매니저 올인원 패키지',
    category_raw: 'PM/PO',
    experience_level: '신입~3년',
    experience_min: 0,
    experience_max: 3,
    employment_type: '온라인 강의',
    location: '온라인',
    jd_text: '현직 PM이 알려주는 실전 강의입니다.\n• 프로덕트 전략 수립\n• 데이터 기반 의사결정\n• 스프린트/애자일 실전',
    requirements: '• 전공 무관\n• 기초 PC 활용 가능',
    company_industry: '에듀테크',
    deadline: null,
    posted_at: days(-14),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['자기계발'],
    created_at: days(-14),
    updated_at: days(-14),
  },
  {
    id: 11,
    source: 'manual',
    source_id: 'mock-11',
    content_type: 'bootcamp',
    url: 'https://codestates.com/course/pm',
    company_name: '코드스테이츠',
    title: 'Product Manager 부트캠프',
    category_raw: 'PM/PO',
    experience_level: '신입/무경력',
    experience_min: 0,
    employment_type: '부트캠프 (오프라인)',
    location: '서울 강남구',
    salary: 'ISA (소득공유) 또는 선불',
    jd_text: '4개월 집중 과정으로 PM 커리어를 시작합니다.\n• 실제 서비스 기획 프로젝트\n• 협업/스프린트 체험\n• 포트폴리오 완성 및 취업 지원',
    requirements: '• 전공 무관, 성인\n• 풀타임 참여 가능',
    company_industry: '에듀테크',
    deadline: days(30),
    posted_at: days(-5),
    is_featured: false,
    is_hidden: false,
    recommendation_tags: ['오프라인', '포트폴리오'],
    created_at: days(-5),
    updated_at: days(-5),
  },
]
